WebShop/ViewModels/CarsListViewModel.cs
using WebShop.Data.Models;
using System.Collections;
using System.Collections.Generic;

namespace WebShop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }

        public string CurrCategory { get; set; }
    }
}

WebShop/ViewModels/HomeViewModel.cs
using WebShop.Data.Models;

namespace WebShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

WebShop/ViewModels/ShopCartViewModel.cs
using WebShop.Data.Models;

namespace WebShop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

WebShop/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Interfaces;
using WebShop.Data.Models;
using WebShop.ViewModels;

namespace WebShop.Controllers
{
    public class CarsController:Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        public CarsController(IAllCars allCars, ICarsCategory carsCategory)
        {
            _allCars = allCars;
            _allCategories = carsCategory;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Car> cars=null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(i => i.id);
            }
            else 
            { 
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Электромобили")).OrderBy(i => i.id);
                    currCategory = "Электромобили";
                }
                    
                else if (string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Классические автомобили")).OrderBy(i => i.id);
                    currCategory = "Классические автомобили";
                }
                    
            }

            
            var carObj = new CarsListViewModel { allCars = cars, CurrCategory = currCategory };

            ViewBag.Title = "Страница с автомобилями";
            

            return View(carObj);
        }

    }
}

WebShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Interfaces;
using WebShop.Data.Models;
using WebShop.ViewModels;

namespace WebShop.Controllers
{
    public class HomeController:Controller
    {
        private readonly IAllCars _carRepozitory;        

        public HomeController(IAllCars carRepozitory)
        {
            _carRepozitory = carRepozitory;         
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                favCars = _carRepozitory.GetFavCars
            };
            return View(homeCars);
        }
    }
}

WebShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Models;
using WebShop.Data;
using WebShop.Data.Interfaces;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace WebShop.Controllers
{
    public class OrderController:Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {

            shopCart.ListShopItem = shopCart.GetShopItems();
            if (ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                                       .Where(y => y.Count > 0)
                                       .ToList();
            }


            if (shopCart.ListShopItem.Count==0)            
                ModelState.AddModelError("", "У вас должны быть товары!");
            
            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

WebShop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Interfaces;
using WebShop.Data.Models;
using WebShop.Data.Repozitory;
using WebShop.ViewModels;

namespace WebShop.Controllers
{
    public class ShopCartController:Controller
    {
        private readonly IAllCars _carRepozitory;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRepozitory, ShopCart shopCart)
        {
            _carRepozitory = carRepozitory;
            _shopCart = shopCart;
        }

        public ViewResult Index2()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItem = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }
        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRepozitory.Cars.FirstOrDefault(i=>i.id == id);
            if (item !=null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index2");
        }
    }
}

WebShop/Views/Cars/List.cshtml
  <h1>Все автомобили</h1>
  <h3>@Model.CurrCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.allCars)         
        @Html.Partial("AllCars",car)
    }
</div>

WebShop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Лучшие автомобили</h1>

<div class="row mt-5 mb-2">
    @{

        foreach (Car car in Model.favCars)
        {   
            @Html.Partial("AllCars",car)
        }

    }
</div>

WebShop/Views/Order/Checkout.cshtml
@model Order

    <h3>Оформление заказа</h3>
    <div class="row mb-5">
        <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Surname"></label>
            <div class="col-md-5">
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address"></label>
            <div class="col-md-5">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-md-5">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success"  type="submit" value="Завершить заказ" />
    </form>

    </div>
   

WebShop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

WebShop/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Добавить в корзину</a></p>
</div>

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">WebProjectZ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Машины</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Электромобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Классические автомобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/index2">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>2022 Все права защищены <a href="#">Соглашение</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

WebShop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container"> 
    @foreach (var el in Model.shopCart.ListShopItem)
    {
        <div class="alert alert-warning mt-3"> 
            <b>Автомобиль: </b> @el.car.name<br/>
            <b>Цена:</b>@el.car.price.ToString("c")
        </div>
    }
    <hr />
    <div class="btn btn-danger" asp-controller="Order">Оплатить</div>
</div>

WebShop/Views/ShopCart/Index2.cshtml
@model ShopCartViewModel

<div class="container"> 
    @foreach (var el in Model.shopCart.ListShopItem)
    {
        <div class="alert alert-warning mt-3"> 
            <b>Автомобиль: </b> @el.car.name<br/>
            <b>Цена:</b>@el.car.price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="CheckOut">Оплатить</a>
</div>